import { Exchange } from './types';

export const EXCHANGES: Exchange[] = [
    {
        id: 'lighter',
        name: 'Lighter',
        description: 'A decentralized perpetuals exchange on Ethereum.',
        makerFee: 'Variable',
        takerFee: 'Variable',
        blockchains: ['Ethereum'],
        websiteUrl: 'https://app.lighter.xyz/',
        tutorialUrl: '#',
    },
    {
        id: 'pacifica',
        name: 'Pacifica',
        description: 'A next-generation fully on-chain perpetuals DEX built on Solana.',
        makerFee: 'Variable',
        takerFee: 'Variable',
        blockchains: ['Solana'],
        websiteUrl: 'https://app.pacifica.fi?referral=aero',
        tutorialUrl: 'https://youtu.be/suBhjL5_-M4?si=yv9P4GeUZqQn8pun',
    },
    {
        id: 'extended',
        name: 'Extended',
        description: 'A hybrid perpetual DEX offering non-custodial trading of perpetual contracts on Starknet.',
        makerFee: 'Variable',
        takerFee: 'Variable',
        blockchains: ['Starknet'],
        websiteUrl: 'https://app.extended.exchange/join/AERO',
        tutorialUrl: 'https://youtu.be/00kBLdooZXU?si=S4xSUnVkNzMSdZMK',
    },
    {
        id: 'edgex',
        name: 'EdgeX',
        description: 'A high-speed trading terminal with direct market access on Arbitrum.',
        makerFee: 'Variable',
        takerFee: 'Variable',
        blockchains: ['Arbitrum'],
        websiteUrl: 'https://pro.edgex.exchange/referral/AERO',
        tutorialUrl: '#',
    },
    {
        id: 'based',
        name: 'BASED',
        description: 'A decentralized exchange powered by Hyperliquid.',
        makerFee: 'Variable',
        takerFee: 'Variable',
        blockchains: ['Hyperliquid'],
        websiteUrl: 'https://app.based.one/register?ref=AERO',
        tutorialUrl: 'https://youtu.be/2pJOBqNDA5A?si=K9t8g1KKkebVl0aN',
    },
    {
        id: 'hyperliquid',
        name: 'Hyperliquid',
        description: 'A decentralized order book perpetuals exchange.',
        makerFee: 'Variable',
        takerFee: 'Variable',
        blockchains: ['Hyperliquid'],
        websiteUrl: 'https://app.hyperliquid.xyz/join/AEROGR',
        tutorialUrl: 'https://youtu.be/2pJOBqNDA5A?si=K9t8g1KKkebVl0aN',
    },
    {
        id: 'paradex',
        name: 'Paradex',
        description: 'A perpetuals DEX built on a Starknet Layer 2, offering deep liquidity and low fees.',
        makerFee: 'Variable',
        takerFee: 'Variable',
        blockchains: ['Starknet'],
        websiteUrl: 'https://app.paradex.trade/r/aerogr',
        tutorialUrl: '#',
    },
    {
        id: 'avantis',
        name: 'Avantis',
        description: 'A decentralized perpetuals trading platform on Base.',
        makerFee: 'Variable',
        takerFee: 'Variable',
        blockchains: ['Base'],
        websiteUrl: 'https://www.avantisfi.com/referral?code=aero',
        tutorialUrl: 'https://youtu.be/WrgQw7YoEz0?si=_HmUuTeEoGTENSzl',
    },
    {
        id: 'apex',
        name: 'Apex',
        description: 'A decentralized and non-custodial derivatives exchange on Arbitrum.',
        makerFee: 'Variable',
        takerFee: 'Variable',
        blockchains: ['Arbitrum'],
        websiteUrl: 'https://omni.apex.exchange/referral?referralCode=GY6XTZ6E',
        tutorialUrl: 'https://youtu.be/ZbQDSL3YvOA?si=ysXgR8g3peI16zpQ',
    },
    {
        id: 'aster',
        name: 'Aster',
        description: 'A multi-chain decentralized exchange supporting Ethereum, BNB Chain, Arbitrum, and Solana.',
        makerFee: 'Variable',
        takerFee: 'Variable',
        blockchains: ['ETH', 'BNB', 'ARB', 'Solana'],
        websiteUrl: 'https://www.asterdex.com/en/referral/748e85',
        tutorialUrl: 'https://youtu.be/04WX_DMuMrM?si=rj-a9fZpc3BgadSV',
    },
    {
        id: 'bullpen',
        name: 'Bullpen',
        description: 'A multi-platform on-chain order book for trading perpetuals.',
        makerFee: 'Variable',
        takerFee: 'Variable',
        blockchains: ['Solana'],
        websiteUrl: '#',
        tutorialUrl: '#',
    },
    {
        id: 'variational',
        name: 'Variational',
        description: 'A decentralized exchange focusing on variational contracts.',
        makerFee: 'Variable',
        takerFee: 'Variable',
        blockchains: ['Ethereum'],
        websiteUrl: '#',
        tutorialUrl: '#',
    },
    {
        id: 'vest',
        name: 'Vest',
        description: 'A platform for decentralized derivatives and perpetuals trading.',
        makerFee: 'Variable',
        takerFee: 'Variable',
        blockchains: ['Arbitrum'],
        websiteUrl: '#',
        tutorialUrl: '#',
    },
    {
        id: 'ostium',
        name: 'Ostium',
        description: 'A decentralized exchange for trading real-world assets.',
        makerFee: 'Variable',
        takerFee: 'Variable',
        blockchains: ['Ethereum'],
        websiteUrl: '#',
        tutorialUrl: '#',
    },
];